import type { PortfolioStatus, AgentRunOut, TradeOut, NewsItem } from "@/lib/api";

export const MOCK_STATUS: PortfolioStatus = {
  id: 1,
  user: "demo",
  cash_balance: 48320.5,
  positions_value: 87234.2,
  total_value: 135554.7,
  unrealized_pnl: 8467.0,
  positions: [
    { symbol: "BTC",  qty: 0.45, avg_price: 62400, current_price: 67850, market_value: 30532.5, unrealized_pnl: 2452.5 },
    { symbol: "ETH",  qty: 4.2,  avg_price: 3100,  current_price: 3380,  market_value: 14196.0, unrealized_pnl: 1176.0 },
    { symbol: "SOL",  qty: 85,   avg_price: 178,   current_price: 195,   market_value: 16575.0, unrealized_pnl: 1445.0 },
    { symbol: "NVDA", qty: 22,   avg_price: 890,   current_price: 1023,  market_value: 22506.0, unrealized_pnl: 2926.0 },
    { symbol: "AAPL", qty: 15,   avg_price: 175,   current_price: 201,   market_value:  3015.0, unrealized_pnl:   390.0 },
  ],
};

// Deterministic 24-point hourly PnL sparkline
export const MOCK_PNL_HISTORY = Array.from({ length: 24 }, (_, i) => ({
  h: `${i}:00`,
  v: 125000 + Math.sin(i * 0.4) * 3200 + i * 420 + (i % 3 === 0 ? -700 : 350),
}));

export const MOCK_LOGS: AgentRunOut[] = [
  {
    id: 4,
    symbol: "BTC",
    analyst: {
      action: "BUY",
      symbol: "BTC",
      reasoning: "RSI oversold at 28.4. Bullish divergence on 4H. Institutional accumulation detected on-chain. Volume profile confirms strong support at current level.",
      confidence: 0.87,
      suggested_pct: 0.15,
      target_price: 71200,
      stop_loss: 64800,
    },
    risk: { approved: true, reason: "Position size within 15% threshold. Risk/reward 1:2.8 — approved.", adjusted_pct: 0.12 },
    executed: true,
    created_at: new Date(Date.now() - 300_000).toISOString(),
  },
  {
    id: 3,
    symbol: "ETH",
    analyst: {
      action: "HOLD",
      symbol: "ETH",
      reasoning: "Consolidating near $3,380 resistance. Waiting for confirmed breakout above $3,420 with volume before adding to position.",
      confidence: 0.62,
      suggested_pct: 0,
      target_price: 3600,
      stop_loss: 3100,
    },
    risk: null,
    executed: false,
    created_at: new Date(Date.now() - 900_000).toISOString(),
  },
  {
    id: 2,
    symbol: "SOL",
    analyst: {
      action: "BUY",
      symbol: "SOL",
      reasoning: "Ecosystem momentum strong. DeFi TVL up 18% WoW. Price action forming cup-and-handle on daily chart. Breakout imminent.",
      confidence: 0.79,
      suggested_pct: 0.1,
      target_price: 230,
      stop_loss: 172,
    },
    risk: { approved: true, reason: "Acceptable risk/reward ratio 1:3.2. Portfolio correlation within limits.", adjusted_pct: 0.08 },
    executed: true,
    created_at: new Date(Date.now() - 1_800_000).toISOString(),
  },
  {
    id: 1,
    symbol: "NVDA",
    analyst: {
      action: "SELL",
      symbol: "NVDA",
      reasoning: "Approaching all-time high resistance. AI capex concerns flagged in earnings call. Short-term overbought on RSI.",
      confidence: 0.71,
      suggested_pct: 0.05,
      target_price: null,
      stop_loss: null,
    },
    risk: { approved: false, reason: "Portfolio under-allocated to AI sector vs benchmark. Overriding SELL — maintaining core position.", adjusted_pct: 0 },
    executed: false,
    created_at: new Date(Date.now() - 3_600_000).toISOString(),
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "btc-1",
    headline: "Bitcoin ETF Inflows Hit Record $1.2B in Single Day as Institutional Demand Surges",
    symbol: "BTC",
    sentiment: "bullish",
    summary: "Institutional adoption accelerating at an unprecedented pace — a strong upside catalyst for BTC price action.",
    sentiment_breakdown: "Bullish for BTC: record ETF inflows signal sustained institutional demand and reduce circulating sell-pressure on spot markets. Capital flowing through regulated vehicles is structurally 'sticky' — it doesn't panic-sell — meaning each new inflow cycle compresses available supply and has a disproportionate upward effect on price. This pattern historically precedes multi-week momentum runs.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Bitcoin+ETF+Inflows+Record+Institutional+Demand&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 2 * 60_000).toISOString(),
  },
  {
    id: "nvda-1",
    headline: "Nvidia Faces EU Antitrust Probe Over AI Chip Market Dominance Concerns",
    symbol: "NVDA",
    sentiment: "bearish",
    summary: "Regulatory headwinds could pressure NVDA margins and slow enterprise AI chip adoption in Europe.",
    sentiment_breakdown: "Bearish for NVDA: antitrust investigations introduce meaningful execution risk — potential remedies range from forced licensing to structural separation, each of which would compress margins or fragment the AI compute moat. Europe represents ~20% of hyperscaler AI capex; even partial restrictions could shave 3–5% from forward revenue estimates and cause multiple compression in the near term.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Nvidia+EU+Antitrust+Probe+AI+Chip&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 7 * 60_000).toISOString(),
  },
  {
    id: "eth-1",
    headline: "Ethereum Foundation Publishes Q3 Roadmap: Pectra Upgrade on Track for September",
    symbol: "ETH",
    sentiment: "bullish",
    summary: "On-time upgrade delivery signals strong developer momentum; potential staking yield improvements ahead.",
    sentiment_breakdown: "Bullish for ETH: the Pectra upgrade bundle improves validator UX and is expected to raise staking APY for smaller validators, which should attract more ETH to be staked and reduce liquid supply. Fewer tokens in circulation create natural price support; additionally, on-time delivery cements the protocol's execution credibility and typically catalyses a re-rating by institutional buyers.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Ethereum+Pectra+Upgrade+Roadmap+Q3&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 14 * 60_000).toISOString(),
  },
  {
    id: "sol-1",
    headline: "Solana DeFi TVL Surpasses $12B for First Time, New Weekly All-Time High",
    symbol: "SOL",
    sentiment: "bullish",
    summary: "Surging DeFi activity on Solana is a fundamental demand driver — bullish for SOL token price.",
    sentiment_breakdown: "Bullish for SOL: rising TVL means more capital is locked in Solana protocols, which generates fee revenue, validator rewards, and — critically — forces market participants to acquire and hold SOL to interact with the ecosystem. A fresh all-time high in TVL signals that developer and user momentum is accelerating rather than plateau-ing, which is a leading indicator of sustained token demand.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Solana+DeFi+TVL+12+Billion+All+Time+High&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 21 * 60_000).toISOString(),
  },
  {
    id: "aapl-1",
    headline: "Apple Intelligence Adoption Crosses 300M Devices; AI Feature Set Expanding in iOS 19",
    symbol: "AAPL",
    sentiment: "bullish",
    summary: "AI-driven upgrade cycle in motion — sets up strong services revenue growth over the next 4 quarters.",
    sentiment_breakdown: "Bullish for AAPL: 300M active AI devices creates a massive installed base for premium services upsell (iCloud+, Apple One, App Store). Each iOS 19 AI feature deepens platform stickiness and drives upgrade cycles among the existing 2B+ device base, directly improving average revenue per user — Apple's highest-margin revenue stream and the key multiple driver for institutional investors.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Apple+Intelligence+300M+Devices+iOS+19&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 35 * 60_000).toISOString(),
  },
  {
    id: "btc-2",
    headline: "U.S. SEC Delays Decision on Spot Bitcoin Options Approval for Third Time",
    symbol: "BTC",
    sentiment: "bearish",
    summary: "Continued regulatory uncertainty caps near-term upside; traders reducing leverage ahead of ruling.",
    sentiment_breakdown: "Bearish for BTC: a third SEC delay signals that regulatory clarity is further away than the market priced in, and elevated uncertainty typically causes leveraged traders to de-risk. Without spot options, large institutional players lack the hedging tools needed to take on bigger long positions — this suppresses the next leg of institutional demand and keeps a ceiling on price until a positive ruling is issued.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=SEC+Spot+Bitcoin+Options+Approval+Delay&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 48 * 60_000).toISOString(),
  },
  {
    id: "msft-1",
    headline: "Microsoft Azure AI Revenue Grows 38% YoY; Copilot Seat Count Doubles in Q2",
    symbol: "MSFT",
    sentiment: "bullish",
    summary: "Cloud AI monetisation is compounding faster than expected, supporting premium valuation multiples.",
    sentiment_breakdown: "Bullish for MSFT: 38% YoY growth in Azure AI revenue outpaces consensus estimates and is the highest-margin workload in the Azure portfolio. Doubling Copilot enterprise seats demonstrates that the AI monetisation thesis is translating to real ARR, not just trials — this justifies premium P/E multiples and sets the stage for upward EPS revisions that typically drive institutional re-allocation into the stock.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Microsoft+Azure+AI+Revenue+Copilot+Growth&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 62 * 60_000).toISOString(),
  },
  {
    id: "tsla-1",
    headline: "Tesla Deliveries Fall Short of Estimates for Second Consecutive Quarter",
    symbol: "TSLA",
    sentiment: "bearish",
    summary: "Demand softness and margin compression remain key bear-case risks for TSLA into year-end.",
    sentiment_breakdown: "Bearish for TSLA: consecutive delivery misses indicate structural demand erosion rather than a one-off supply issue, which undermines the high-growth narrative that supports the stock's premium valuation. Management will likely be forced to cut ASPs further to clear inventory, compressing automotive margins which are already under pressure — a double negative for forward earnings estimates.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Tesla+Delivery+Miss+Consecutive+Quarter&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 80 * 60_000).toISOString(),
  },
  {
    id: "eth-2",
    headline: "Ethereum Staking Ratio Holds Steady at 27%; No Unusual Unstaking Activity Detected",
    symbol: "ETH",
    sentiment: "neutral",
    summary: "Stable staking metrics reflect network maturity; no near-term supply shock expected.",
    sentiment_breakdown: "Neutral for ETH: a steady staking ratio means the supply/demand dynamic is not changing materially — there is no incoming supply shock from mass unstaking, but also no incremental demand catalyst. This reflects network maturity rather than momentum; price action will likely remain range-bound until an external catalyst (protocol upgrade, macro shift, or ETF inflow) changes the balance.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Ethereum+Staking+Ratio+27+Percent+Network&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 95 * 60_000).toISOString(),
  },
  {
    id: "nvda-2",
    headline: "Nvidia Launches Blackwell Ultra GPU Sampling Program for Tier-1 Cloud Partners",
    symbol: "NVDA",
    sentiment: "bullish",
    summary: "Early Blackwell adoption by hyperscalers is a near-term revenue accelerant for NVDA.",
    sentiment_breakdown: "Bullish for NVDA: Tier-1 hyperscaler sampling is typically the last step before full production orders are placed, suggesting a meaningful revenue inflection is 1–2 quarters away. Blackwell Ultra delivers significantly higher compute density per dollar than Hopper, which means hyperscalers have a clear ROI case to accelerate capex — each GPU rack upgrade is a direct NVDA revenue event at higher ASPs than the previous generation.",
    source: "Market Intelligence",
    url: "https://news.google.com/search?q=Nvidia+Blackwell+Ultra+GPU+Cloud+Partners&hl=en&gl=US&ceid=US:en",
    published_at: new Date(Date.now() - 108 * 60_000).toISOString(),
  },
];

export const MOCK_TRADES: TradeOut[] = [
  {
    id: 4,
    symbol: "BTC",
    side: "BUY",
    qty: 0.15,
    price: 67200,
    rationale: "Bullish RSI divergence + institutional flow detected on-chain. Entry timed with 4H structure break.",
    created_at: new Date(Date.now() - 320_000).toISOString(),
  },
  {
    id: 3,
    symbol: "SOL",
    side: "BUY",
    qty: 20,
    price: 190,
    rationale: "Cup-and-handle confirmed on daily. DeFi TVL momentum strong, targeting $230 with stop at $172.",
    created_at: new Date(Date.now() - 1_820_000).toISOString(),
  },
  {
    id: 2,
    symbol: "ETH",
    side: "SELL",
    qty: 1.5,
    price: 3320,
    rationale: "Partial profit-taking ahead of $3,380 resistance. Maintaining 70% core position for continuation play.",
    created_at: new Date(Date.now() - 86_400_000).toISOString(),
  },
  {
    id: 1,
    symbol: "AAPL",
    side: "BUY",
    qty: 5,
    price: 197,
    rationale: "Services revenue beat expectations. AI integration roadmap is a positive catalyst for the next two quarters.",
    created_at: new Date(Date.now() - 172_800_000).toISOString(),
  },
];
